name: anlp
channels:
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - asn1crypto=0.24.0=py37_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.11.29=py37_0
  - cffi=1.11.5=py37h6174b99_1
  - chardet=3.0.4=py37_1
  - cryptography=2.4.2=py37ha12b0ac_0
  - cymem=1.31.2=py37h04f5b5a_0
  - cytoolz=0.9.0.1=py37h1de35cc_1
  - decorator=4.3.0=py37_0
  - dill=0.2.8.2=py37_0
  - entrypoints=0.2.3=py37_2
  - idna=2.8=py37_0
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.2.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.13.2=py37_0
  - jinja2=2.10=py37_0
  - jsonschema=2.6.0=py37_0
  - jupyter_client=5.2.4=py37_0
  - jupyter_core=4.4.0=py37_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libsodium=1.0.16=h3efe00b_0
  - markupsafe=1.1.0=py37h1de35cc_0
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.1=144
  - mkl_random=1.0.2=py37h27c97d8_0
  - msgpack-numpy=0.4.3.2=py37_0
  - msgpack-python=0.5.6=py37h04f5b5a_1
  - murmurhash=0.28.0=py37h0a44026_0
  - nb_conda=2.2.1=py37_0
  - nb_conda_kernels=2.2.0=py37_0
  - nbconvert=5.3.1=py37_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - nltk=3.4=py37_1
  - notebook=5.7.4=py37_0
  - numpy=1.11.3=py37hacdab7b_12
  - numpy-base=1.11.3=py37h6575580_12
  - openssl=1.1.1a=h1de35cc_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.3.1=py37_0
  - pexpect=4.6.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=18.1=py37_0
  - plac=0.9.6=py37_0
  - preshed=1.0.1=py37h0a44026_0
  - prometheus_client=0.5.0=py37_0
  - prompt_toolkit=2.0.7=py37_0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.3.1=py37_0
  - pyopenssl=18.0.0=py37_0
  - pysocks=1.6.8=py37_0
  - python=3.7.2=haf84260_0
  - python-dateutil=2.7.5=py37_0
  - pyzmq=17.1.2=py37h1de35cc_0
  - readline=7.0=h1de35cc_5
  - regex=2018.06.21=py37h1de35cc_0
  - requests=2.21.0=py37_0
  - scikit-learn=0.20.2=py37h27c97d8_0
  - scipy=1.1.0=py37h1410ff5_2
  - send2trash=1.5.0=py37_0
  - setuptools=40.6.3=py37_0
  - six=1.12.0=py37_0
  - spacy=2.0.12=py37h6440ff4_0
  - sqlite=3.26.0=ha441bb4_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.1=py37_1
  - testpath=0.4.2=py37_0
  - thinc=6.10.3=py37h6440ff4_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.9.0=py37_0
  - tornado=5.1.1=py37h1de35cc_0
  - tqdm=4.28.1=py37h28b3542_0
  - traitlets=4.3.2=py37_0
  - ujson=1.35=py37h1de35cc_0
  - urllib3=1.24.1=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.32.3=py37_0
  - wrapt=1.10.11=py37h1de35cc_2
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.2.5=h0a44026_1
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - en-core-web-sm==2.0.0
    - msgpack==0.5.6

